- name: Install dependencies
        run: |
          pip install --upgrade pip
          # バイナリを優先的にインストールすることでビルドエラーを回避
          pip install --only-binary :all: numpy pandas
          pip install yfinance requests pandas_market_calendars pandas_ta alpaca-py
