- name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --only-binary :all: numpy pandas
          pip install yfinance requests pandas_market_calendars ta alpaca-py pytz
